- name: Deploy'ing Docker infrastructure on OpenStack
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Deploy docker host
      os_server:
        state: present
        name: SANITIZED
        image: SANIZIED
        key_name: SANITIZED
        wait: yes
        flavor: A1.4
        # auto_floating_ip: no
        nics:
          # port-id requires up to date shade package as of 06-2017
          # requires neutron port to be created: http://bit.ly/2seqyV4
          - port-id: 0dab595e-8c46-LONGSTRING
          - net-name: inap-NETWORKNAME
        security_groups:
          - default
          - global_egress
          - webserver_allowed
        meta:
          hostname: SANITIZED

    - name : Deploy SWIFT Object Store Container
      os_object:
        container: SANITIZED`
        state: present
        wait: no
